#!/bin/sh
set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
    # Update icon cache
    if which gtk-update-icon-cache >/dev/null 2>&1 ; then
        gtk-update-icon-cache -f -t /usr/share/icons/hicolor || true
    fi
fi

#DEBHELPER#

exit 0